### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by Guisfc** [devhid/PEX-Rankup#1]
Eu queria muito usar esse plugin, porém mesmo utilizando o Vault aparece o seguinte erro: 

[PEX-Rankup] Enabling PEX-Rankup v2.0
[PEX-Rankup] Disabled due to lack of Vault dependency.
[PEX-Rankup] Disabling PEX-Rankup v2.0

Me ajuda por favor!

**Comment by devhid** [comment]
This happens because Vault needs an economy plugin to attach to.  Installing Essentials or any other plugin that handles economy will fix the issue.
