### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Pukmwoan** [devhid/PEX-Rankup#12]
Hey,

How can i add the permission to a rank? My rank is called Zone2 but how can i add the permission multiverse.teleport.self.Zone2 or multiverse.portal.acces.Zone2 to the bought rank?

**Comment by devhid** [comment]
The ranks in PEX-Rankup should correspond to the groups you specify in PermissionsEX.

So, you should have a group in PEX called **Zone2** and have `multiverse.teleport.self.Zone2` be one of the permissions for that group. 

PEX-Rankup only sets someone's rank, it doesn't set permissions. That job is for PermissionsEx.

**Comment by Pukmwoan** [comment]
Thanks for the response, despite the fact that I don’t need the plug in anymore!

Puk Roodnat

On 19 Aug 2018, at 22:41, Mikey G <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #12<https://github.com/devhid/PEX-Rankup/issues/12>.
