### ISSUE TITLE
De ranking

### ISSUE THREAD

**Issue by GameCrunch** [devhid/PEX-Rankup#14]
Hi! 
Im setting up a server and im having an issue where every so often when i reload its demoting ranks?
Like for instants if my laddder is as followed
Knight 
Ledgend 
Lord
and a player is lord, when i reload they end up as Ledged 
I hope this issue can be solved because i really love your plugin,
thanks for your help

**Comment by devhid** [comment]
Hi, make sure you use /pr-reload instead of /reload.

**Comment by GameCrunch** [comment]
Does that command do server wide reload or just the plugin reload ?

**Comment by devhid** [comment]
It does a plugin reload. If you use /reload, that might be the reason why you’re having issues.

You should use a plugin like Plugman to reload other individual plugins.

**Comment by GameCrunch** [comment]
ah ok, thank you for the advice , ill have to give it a try

**Comment by devhid** [comment]
Going to close this. If you run into an issue, please open a new issue.
