### ISSUE TITLE
Placeholder issue

### ISSUE THREAD

**Issue by maxlehot1234** [devhid/PEX-Rankup#7]
Hi, It,s just to told you that the placeholder sometimes stop working completely and I need to restart the server.
No error in the console or in the chat...

![image](https://cloud.githubusercontent.com/assets/5159244/19405601/611013f0-9247-11e6-849b-d21b76dad819.png)

I can create an issue for all bugs/suggesiton listed on spigot if you prefer ;)

Thanks again

**Comment by maxlehot1234** [comment]
@devhid This is the error I have after trying to reload featherboard:
http://pastebin.com/ySqdtUsT

It happens when I reach the LAST RANK on my server...
If you can add an option to display max rank reach and allow us to edit it, this will fix this error, I think

Any ETA for the next release ?

**Comment by maxlehot1234** [comment]
Just to told you that this happen randomly sometimes...

**Comment by devhid** [comment]
Does this issue still happen with the new updates I just released?

**Comment by maxlehot1234** [comment]
It seem to be fine now. But I confirm later today when 100 players join the server ;)

**Comment by maxlehot1234** [comment]
@devhid 
Same problem with new version and it also break the TokenEnchant (latest version) placeholder when the player reach the last rank...
https://www.spigotmc.org/resources/papi-tokenenchanttoken.30722/

Doesn't know why, but doesn't happen before...

**Comment by SBUWebAndAppClub** [comment]
Did you put the new RankupExpansion.jar in your plugins\PlaceholderAPI\expansions folder?


If you did, try typing in: /papi reload

See if that worked. If it didn't let me know.

**Comment by devhid** [comment]
Did you put the new RankupExpansion.jar in your plugins\PlaceholderAPI\expansions folder?

If you did, try typing in: /papi reload

See if that worked. If it didn't let me know.

**Comment by maxlehot1234** [comment]
@devhid 
Same issue when player reach the last rank. I add 5 more ranks on my server so I am good for the moment until a player reach the last rank.

**Comment by devhid** [comment]
What error appears in console when someone tries to reach the last rank?

**Comment by maxlehot1234** [comment]
@devhid 
Sorry, I am away of my computer during the day...

This is the error I have in the console when I reach the last rank.
http://pastebin.com/uC7YkC8a

**Comment by devhid** [comment]
I fixed this though...

Ok, I know you're probably bothering you at this point but are you sure you updated BOTH PEX-Rankup and RankupExpansion?

**Comment by maxlehot1234** [comment]
@devhid Yes I am 100000% sure that I have latest version, I already check...
Only happen when a player reach the last rank and the placheolder stop working for all online players until the players leave. Few minutes after scoreboard go back to normal and the placeholder works again

**Comment by devhid** [comment]
I contacted the developer for Featherboard in hopes that he will give me a copy of his plugin for free so I can try to replicate your problem. I tested this bug with SpigotBoard and it worked fine so I thought it would work fine for Featherboard.

I will get back to you once I get a hold of a developer copy.

**Comment by maxlehot1234** [comment]
@devhid Check your Pm your Spigot

And maxim will never give his plugin I think. He was a really great dev, but which (BIG) devs give their plugins for free?
