### ISSUE TITLE
[suggestions] PEX-Rankup

### ISSUE THREAD

**Issue by maxlehot1234** [devhid/PEX-Rankup#8]
HI, I have few suggestions for you when you have time:

1-) Are you able to add a new placeholder to allow players to see moeny needed before the next rank?
2-) Are you able to add a rankup cost reduction permission?

Thank you :)

**Comment by devhid** [comment]
1) Yes, I'll add that.
2) No. This feature seems a bit more specific to your needs and not really applicable to many others. Sorry.

**Comment by maxlehot1234** [comment]
1-) Ok
2-) Maybe my dev can create this system

The rankup events was ready in the new pexrankup version or not available now?

Thanks again

**Comment by devhid** [comment]
It will be in the next update. It's extremely easy to add.

**Comment by maxlehot1234** [comment]
Ok thank you ;)
